on:
  workflow_dispatch:

name: Publish

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          
      - name: Cargo Install Bump
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: bump
      
      - name: Bump
        uses: actions-rs/cargo@v1
        with:
          command: bump
          args: minor --git-tag

      - run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
